package InterfaceGrafica;

import ConexionBD.ConexionBaseDatos;
import ConexionBD.Partida;
import Xogo.Cadrados.Cadrado;
import Xogo.Xogo;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author a22noellr
 */
public class Interface extends javax.swing.JFrame {
    private Xogo xogo;
    private ConexionBaseDatos conexionBD;
    private Timer timer;
    private Timer tempoXogo;
    private int delay = 500;
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        xogo = new Xogo(this);
        conexionBD = new ConexionBaseDatos(this);
        crearTimerVelocidade();
        crearTempoXogo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDModoXogo = new javax.swing.JDialog();
        panelModoXogo = new javax.swing.JPanel();
        bClasico = new javax.swing.JButton();
        bEsfera = new javax.swing.JButton();
        jDGardarPuntuacion = new javax.swing.JDialog();
        panelGardarPuntuacion = new javax.swing.JPanel();
        bIniciarSesión = new javax.swing.JButton();
        bRegistrarse = new javax.swing.JButton();
        bConfirmarGardarPuntuacion = new javax.swing.JButton();
        lblComoUsuario = new javax.swing.JLabel();
        jDSesion = new javax.swing.JDialog();
        panelInicioSesion = new javax.swing.JPanel();
        usuario = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        lblContrasinal = new javax.swing.JLabel();
        contrasinal = new javax.swing.JTextField();
        bConfirmarInicioSesion = new javax.swing.JButton();
        lblUsuarioNonEncontrado = new javax.swing.JLabel();
        tituloInicioSesion = new javax.swing.JLabel();
        panelRegistrarse = new javax.swing.JPanel();
        usuarioNovo = new javax.swing.JTextField();
        lblUsuarioNovo = new javax.swing.JLabel();
        lblContrasinalNovo = new javax.swing.JLabel();
        contrasinalNovo = new javax.swing.JTextField();
        bConfirmarRegistrarse = new javax.swing.JButton();
        tituloRegistrarse = new javax.swing.JLabel();
        lblUsuarioOcupado = new javax.swing.JLabel();
        pantallaInicial = new javax.swing.JPanel();
        tituloSerpe = new javax.swing.JLabel();
        bIniciar = new javax.swing.JButton();
        bModoXogo = new javax.swing.JButton();
        bPuntuacions = new javax.swing.JButton();
        bSairXogo = new javax.swing.JButton();
        juego = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        tituloMenuSerpe = new javax.swing.JLabel();
        lblBombas = new javax.swing.JLabel();
        lblFroitas = new javax.swing.JLabel();
        bombasComidas = new javax.swing.JLabel();
        lblTempo = new javax.swing.JLabel();
        tempoXogado = new javax.swing.JLabel();
        froitasComidas = new javax.swing.JLabel();
        bPausa = new javax.swing.JToggleButton();
        puntosObtidos = new javax.swing.JLabel();
        lblPuntuacion = new javax.swing.JLabel();
        panelXogo = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        panelFinXogo = new javax.swing.JPanel();
        tituloFinXogo = new javax.swing.JLabel();
        bPantallaInicial = new javax.swing.JButton();
        bNovaPartida = new javax.swing.JButton();
        bGardarPuntuacion = new javax.swing.JButton();
        panelPuntuacions = new javax.swing.JPanel();
        tituloSerpe1 = new javax.swing.JLabel();
        bVolverInicio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePuntuacions = new javax.swing.JTable();

        jDModoXogo.setVisible(false);
        jDModoXogo.setTitle("Modo de Xogo");
        jDModoXogo.setBackground(new java.awt.Color(182, 255, 182));
        jDModoXogo.setForeground(new java.awt.Color(182, 255, 182));
        jDModoXogo.setIconImage(getIconImage());
        jDModoXogo.setLocation(new java.awt.Point(350, 300));
        jDModoXogo.setMinimumSize(new java.awt.Dimension(400, 400));
        jDModoXogo.setResizable(false);
        jDModoXogo.setSize(new java.awt.Dimension(400, 400));

        panelModoXogo.setBackground(new java.awt.Color(102, 204, 0));
        panelModoXogo.setMaximumSize(new java.awt.Dimension(400, 400));
        panelModoXogo.setMinimumSize(new java.awt.Dimension(400, 400));
        panelModoXogo.setPreferredSize(new java.awt.Dimension(400, 400));

        bClasico.setBackground(new java.awt.Color(102, 204, 255));
        bClasico.setFont(new java.awt.Font("Reem Kufi", 0, 24)); // NOI18N
        bClasico.setForeground(new java.awt.Color(102, 0, 102));
        bClasico.setText("CLÁSICO");
        bClasico.setMaximumSize(new java.awt.Dimension(200, 50));
        bClasico.setMinimumSize(new java.awt.Dimension(200, 50));
        bClasico.setPreferredSize(new java.awt.Dimension(200, 50));
        bClasico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClasicoActionPerformed(evt);
            }
        });

        bEsfera.setBackground(new java.awt.Color(102, 204, 255));
        bEsfera.setFont(new java.awt.Font("Reem Kufi", 0, 24)); // NOI18N
        bEsfera.setForeground(new java.awt.Color(102, 0, 102));
        bEsfera.setText("ESFERA");
        bEsfera.setMaximumSize(new java.awt.Dimension(200, 50));
        bEsfera.setMinimumSize(new java.awt.Dimension(200, 50));
        bEsfera.setPreferredSize(new java.awt.Dimension(200, 50));
        bEsfera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEsferaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelModoXogoLayout = new javax.swing.GroupLayout(panelModoXogo);
        panelModoXogo.setLayout(panelModoXogoLayout);
        panelModoXogoLayout.setHorizontalGroup(
            panelModoXogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModoXogoLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(panelModoXogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(bEsfera, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(bClasico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(99, 99, 99))
        );
        panelModoXogoLayout.setVerticalGroup(
            panelModoXogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModoXogoLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(bClasico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(bEsfera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDModoXogoLayout = new javax.swing.GroupLayout(jDModoXogo.getContentPane());
        jDModoXogo.getContentPane().setLayout(jDModoXogoLayout);
        jDModoXogoLayout.setHorizontalGroup(
            jDModoXogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDModoXogoLayout.createSequentialGroup()
                .addComponent(panelModoXogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jDModoXogoLayout.setVerticalGroup(
            jDModoXogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDModoXogoLayout.createSequentialGroup()
                .addComponent(panelModoXogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jDGardarPuntuacion.setVisible(false);
        jDGardarPuntuacion.setLocation(350, 100);
        jDGardarPuntuacion.setTitle("Gardar Puntuación");
        jDGardarPuntuacion.setIconImage(getIconImage());
        jDGardarPuntuacion.setMinimumSize(new java.awt.Dimension(700, 700));
        jDGardarPuntuacion.setResizable(false);

        panelGardarPuntuacion.setBackground(new java.awt.Color(182, 255, 182));
        panelGardarPuntuacion.setMaximumSize(new java.awt.Dimension(700, 700));
        panelGardarPuntuacion.setMinimumSize(new java.awt.Dimension(700, 700));
        panelGardarPuntuacion.setPreferredSize(new java.awt.Dimension(700, 700));

        bIniciarSesión.setBackground(new java.awt.Color(102, 204, 255));
        bIniciarSesión.setFont(new java.awt.Font("Reem Kufi", 0, 24)); // NOI18N
        bIniciarSesión.setForeground(new java.awt.Color(102, 0, 102));
        bIniciarSesión.setText("INICIAR SESIÓN");
        bIniciarSesión.setMaximumSize(new java.awt.Dimension(200, 50));
        bIniciarSesión.setMinimumSize(new java.awt.Dimension(200, 50));
        bIniciarSesión.setPreferredSize(new java.awt.Dimension(200, 50));
        bIniciarSesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIniciarSesiónActionPerformed(evt);
            }
        });

        bRegistrarse.setBackground(new java.awt.Color(102, 204, 255));
        bRegistrarse.setFont(new java.awt.Font("Reem Kufi", 0, 24)); // NOI18N
        bRegistrarse.setForeground(new java.awt.Color(102, 0, 102));
        bRegistrarse.setText("REGISTRARSE");
        bRegistrarse.setMaximumSize(new java.awt.Dimension(200, 50));
        bRegistrarse.setMinimumSize(new java.awt.Dimension(200, 50));
        bRegistrarse.setPreferredSize(new java.awt.Dimension(200, 50));
        bRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarseActionPerformed(evt);
            }
        });

        bConfirmarGardarPuntuacion.setBackground(new java.awt.Color(102, 204, 255));
        bConfirmarGardarPuntuacion.setFont(new java.awt.Font("Reem Kufi", 0, 24)); // NOI18N
        bConfirmarGardarPuntuacion.setForeground(new java.awt.Color(102, 0, 102));
        bConfirmarGardarPuntuacion.setText(" GARDAR PUNTUACIÓN");
        bConfirmarGardarPuntuacion.setMaximumSize(new java.awt.Dimension(200, 50));
        bConfirmarGardarPuntuacion.setMinimumSize(new java.awt.Dimension(200, 50));
        bConfirmarGardarPuntuacion.setPreferredSize(new java.awt.Dimension(200, 50));
        bConfirmarGardarPuntuacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConfirmarGardarPuntuacionActionPerformed(evt);
            }
        });

        lblComoUsuario.setFont(new java.awt.Font("Reem Kufi", 0, 18)); // NOI18N
        lblComoUsuario.setForeground(new java.awt.Color(102, 0, 102));
        lblComoUsuario.setText("Como invitado");

        javax.swing.GroupLayout panelGardarPuntuacionLayout = new javax.swing.GroupLayout(panelGardarPuntuacion);
        panelGardarPuntuacion.setLayout(panelGardarPuntuacionLayout);
        panelGardarPuntuacionLayout.setHorizontalGroup(
            panelGardarPuntuacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGardarPuntuacionLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(bIniciarSesión, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(bRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
            .addGroup(panelGardarPuntuacionLayout.createSequentialGroup()
                .addGroup(panelGardarPuntuacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGardarPuntuacionLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(bConfirmarGardarPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGardarPuntuacionLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(lblComoUsuario)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGardarPuntuacionLayout.setVerticalGroup(
            panelGardarPuntuacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGardarPuntuacionLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(panelGardarPuntuacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bIniciarSesión, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(163, 163, 163)
                .addComponent(bConfirmarGardarPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblComoUsuario)
                .addContainerGap(271, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDGardarPuntuacionLayout = new javax.swing.GroupLayout(jDGardarPuntuacion.getContentPane());
        jDGardarPuntuacion.getContentPane().setLayout(jDGardarPuntuacionLayout);
        jDGardarPuntuacionLayout.setHorizontalGroup(
            jDGardarPuntuacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGardarPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDGardarPuntuacionLayout.setVerticalGroup(
            jDGardarPuntuacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGardarPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jDSesion.setVisible(false);
        jDSesion.setLocation(100, 100);
        jDSesion.setTitle("Sesión");
        jDSesion.setIconImage(getIconImage());
        jDSesion.setMinimumSize(new java.awt.Dimension(500, 500));
        jDSesion.setResizable(false);

        panelInicioSesion.setVisible(false);
        panelInicioSesion.setBackground(new java.awt.Color(182, 255, 182));
        panelInicioSesion.setMaximumSize(new java.awt.Dimension(500, 500));
        panelInicioSesion.setMinimumSize(new java.awt.Dimension(500, 500));
        panelInicioSesion.setPreferredSize(new java.awt.Dimension(500, 500));

        usuario.setBackground(new java.awt.Color(102, 204, 255));

        lblUsuario.setFont(new java.awt.Font("Reem Kufi", 0, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(102, 0, 102));
        lblUsuario.setText("Inserte o seu usuario:");

        lblContrasinal.setFont(new java.awt.Font("Reem Kufi", 0, 18)); // NOI18N
        lblContrasinal.setForeground(new java.awt.Color(102, 0, 102));
        lblContrasinal.setText("Inserte o seu contrasinal:");

        contrasinal.setBackground(new java.awt.Color(102, 204, 255));

        bConfirmarInicioSesion.setBackground(new java.awt.Color(102, 204, 255));
        bConfirmarInicioSesion.setFont(new java.awt.Font("Reem Kufi", 0, 14)); // NOI18N
        bConfirmarInicioSesion.setForeground(new java.awt.Color(102, 0, 102));
        bConfirmarInicioSesion.setText("INICIAR SESION");
        bConfirmarInicioSesion.setMaximumSize(new java.awt.Dimension(200, 50));
        bConfirmarInicioSesion.setMinimumSize(new java.awt.Dimension(200, 50));
        bConfirmarInicioSesion.setPreferredSize(new java.awt.Dimension(200, 50));
        bConfirmarInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConfirmarInicioSesionActionPerformed(evt);
            }
        });

        lblUsuarioNonEncontrado.setFont(new java.awt.Font("Reem Kufi", 0, 18)); // NOI18N
        lblUsuarioNonEncontrado.setForeground(new java.awt.Color(102, 0, 102));

        tituloInicioSesion.setBackground(new java.awt.Color(153, 0, 153));
        tituloInicioSesion.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        tituloInicioSesion.setForeground(new java.awt.Color(153, 0, 153));
        tituloInicioSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloInicioSesion.setText("Inicio de Sesión");

        javax.swing.GroupLayout panelInicioSesionLayout = new javax.swing.GroupLayout(panelInicioSesion);
        panelInicioSesion.setLayout(panelInicioSesionLayout);
        panelInicioSesionLayout.setHorizontalGroup(
            panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioSesionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelInicioSesionLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUsuarioNonEncontrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contrasinal)
                    .addComponent(lblContrasinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usuario)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bConfirmarInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(234, Short.MAX_VALUE))
        );

        panelInicioSesionLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {contrasinal, lblContrasinal, lblUsuario, usuario});

        panelInicioSesionLayout.setVerticalGroup(
            panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioSesionLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tituloInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblContrasinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contrasinal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(bConfirmarInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUsuarioNonEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        panelInicioSesionLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {contrasinal, lblContrasinal, lblUsuario, usuario});

        panelRegistrarse.setVisible(false);
        panelRegistrarse.setBackground(new java.awt.Color(182, 255, 182));
        panelRegistrarse.setMaximumSize(new java.awt.Dimension(500, 500));
        panelRegistrarse.setMinimumSize(new java.awt.Dimension(500, 500));

        usuarioNovo.setBackground(new java.awt.Color(102, 204, 255));

        lblUsuarioNovo.setFont(new java.awt.Font("Reem Kufi", 0, 18)); // NOI18N
        lblUsuarioNovo.setForeground(new java.awt.Color(102, 0, 102));
        lblUsuarioNovo.setText("Inserte un nome de usuario:");

        lblContrasinalNovo.setFont(new java.awt.Font("Reem Kufi", 0, 18)); // NOI18N
        lblContrasinalNovo.setForeground(new java.awt.Color(102, 0, 102));
        lblContrasinalNovo.setText("Inserte un contrasinal:");

        contrasinalNovo.setBackground(new java.awt.Color(102, 204, 255));

        bConfirmarRegistrarse.setBackground(new java.awt.Color(102, 204, 255));
        bConfirmarRegistrarse.setFont(new java.awt.Font("Reem Kufi", 0, 14)); // NOI18N
        bConfirmarRegistrarse.setForeground(new java.awt.Color(102, 0, 102));
        bConfirmarRegistrarse.setText("REGISTRARSE");
        bConfirmarRegistrarse.setMaximumSize(new java.awt.Dimension(200, 50));
        bConfirmarRegistrarse.setMinimumSize(new java.awt.Dimension(200, 50));
        bConfirmarRegistrarse.setPreferredSize(new java.awt.Dimension(200, 50));
        bConfirmarRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConfirmarRegistrarseActionPerformed(evt);
            }
        });

        tituloRegistrarse.setBackground(new java.awt.Color(153, 0, 153));
        tituloRegistrarse.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        tituloRegistrarse.setForeground(new java.awt.Color(153, 0, 153));
        tituloRegistrarse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloRegistrarse.setText("Registrarse");

        lblUsuarioOcupado.setFont(new java.awt.Font("Reem Kufi", 0, 18)); // NOI18N
        lblUsuarioOcupado.setForeground(new java.awt.Color(102, 0, 102));

        javax.swing.GroupLayout panelRegistrarseLayout = new javax.swing.GroupLayout(panelRegistrarse);
        panelRegistrarse.setLayout(panelRegistrarseLayout);
        panelRegistrarseLayout.setHorizontalGroup(
            panelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarseLayout.createSequentialGroup()
                .addGroup(panelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistrarseLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(panelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contrasinalNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblContrasinalNovo)
                            .addComponent(usuarioNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsuarioNovo)
                            .addComponent(bConfirmarRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsuarioOcupado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelRegistrarseLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(tituloRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                .addGap(168, 168, 168))
        );

        panelRegistrarseLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {contrasinalNovo, lblContrasinalNovo, lblUsuarioNovo, usuarioNovo});

        panelRegistrarseLayout.setVerticalGroup(
            panelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarseLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(tituloRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUsuarioNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usuarioNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblContrasinalNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contrasinalNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(bConfirmarRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUsuarioOcupado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        panelRegistrarseLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {contrasinalNovo, lblContrasinalNovo, lblUsuarioNovo, usuarioNovo});

        javax.swing.GroupLayout jDSesionLayout = new javax.swing.GroupLayout(jDSesion.getContentPane());
        jDSesion.getContentPane().setLayout(jDSesionLayout);
        jDSesionLayout.setHorizontalGroup(
            jDSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(jDSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDSesionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jDSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDSesionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jDSesionLayout.setVerticalGroup(
            jDSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(jDSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDSesionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jDSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDSesionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Serpe");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(1150, 900));
        setMinimumSize(new java.awt.Dimension(1150, 900));
        setResizable(false);
        setSize(new java.awt.Dimension(1150, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pantallaInicial.setBackground(new java.awt.Color(182, 255, 182));
        pantallaInicial.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(80, 40, 0)));
        pantallaInicial.setMaximumSize(new java.awt.Dimension(1150, 900));
        pantallaInicial.setMinimumSize(new java.awt.Dimension(1150, 900));
        pantallaInicial.setPreferredSize(new java.awt.Dimension(1150, 900));

        tituloSerpe.setBackground(new java.awt.Color(153, 0, 153));
        tituloSerpe.setFont(new java.awt.Font("Trebuchet MS", 3, 70)); // NOI18N
        tituloSerpe.setForeground(new java.awt.Color(153, 0, 153));
        tituloSerpe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloSerpe.setText("SERPE");

        bIniciar.setBackground(new java.awt.Color(102, 204, 255));
        bIniciar.setFont(new java.awt.Font("Reem Kufi", 0, 24)); // NOI18N
        bIniciar.setForeground(new java.awt.Color(102, 0, 102));
        bIniciar.setText("INICIAR");
        bIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIniciarActionPerformed(evt);
            }
        });

        bModoXogo.setBackground(new java.awt.Color(102, 204, 255));
        bModoXogo.setFont(new java.awt.Font("Reem Kufi", 0, 24)); // NOI18N
        bModoXogo.setForeground(new java.awt.Color(102, 0, 102));
        bModoXogo.setText("MODO DE XOGO");
        bModoXogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModoXogoActionPerformed(evt);
            }
        });

        bPuntuacions.setBackground(new java.awt.Color(102, 204, 255));
        bPuntuacions.setFont(new java.awt.Font("Reem Kufi", 0, 24)); // NOI18N
        bPuntuacions.setForeground(new java.awt.Color(102, 0, 102));
        bPuntuacions.setText("VER PUNTUACIÓNS");
        bPuntuacions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPuntuacionsActionPerformed(evt);
            }
        });

        bSairXogo.setBackground(new java.awt.Color(102, 204, 255));
        bSairXogo.setFont(new java.awt.Font("Reem Kufi", 0, 24)); // NOI18N
        bSairXogo.setForeground(new java.awt.Color(102, 0, 102));
        bSairXogo.setText("SAÍR DO XOGO");
        bSairXogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairXogoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pantallaInicialLayout = new javax.swing.GroupLayout(pantallaInicial);
        pantallaInicial.setLayout(pantallaInicialLayout);
        pantallaInicialLayout.setHorizontalGroup(
            pantallaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantallaInicialLayout.createSequentialGroup()
                .addGap(421, 421, 421)
                .addGroup(pantallaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tituloSerpe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bModoXogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bPuntuacions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bSairXogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(443, 443, 443))
        );
        pantallaInicialLayout.setVerticalGroup(
            pantallaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantallaInicialLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(tituloSerpe)
                .addGap(94, 94, 94)
                .addComponent(bIniciar)
                .addGap(50, 50, 50)
                .addComponent(bModoXogo)
                .addGap(50, 50, 50)
                .addComponent(bPuntuacions)
                .addGap(50, 50, 50)
                .addComponent(bSairXogo)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        getContentPane().add(pantallaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        juego.setVisible(false);
        juego.setMaximumSize(new java.awt.Dimension(1150, 900));
        juego.setMinimumSize(new java.awt.Dimension(1150, 900));
        juego.setPreferredSize(new java.awt.Dimension(1150, 900));

        menu.setLocation(0, 0);
        menu.setBackground(new java.awt.Color(0, 102, 51));
        menu.setFocusable(false);
        menu.setMaximumSize(new java.awt.Dimension(250, 900));
        menu.setMinimumSize(new java.awt.Dimension(250, 900));
        menu.setName(""); // NOI18N
        menu.setPreferredSize(new java.awt.Dimension(250, 900));

        tituloMenuSerpe.setBackground(new java.awt.Color(153, 0, 153));
        tituloMenuSerpe.setFont(new java.awt.Font("Trebuchet MS", 3, 70)); // NOI18N
        tituloMenuSerpe.setForeground(new java.awt.Color(255, 0, 204));
        tituloMenuSerpe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloMenuSerpe.setText("SERPE");

        lblBombas.setFont(new java.awt.Font("Reem Kufi", 3, 24)); // NOI18N
        lblBombas.setForeground(new java.awt.Color(0, 0, 0));
        lblBombas.setText("BOMBAS");

        lblFroitas.setFont(new java.awt.Font("Reem Kufi", 3, 24)); // NOI18N
        lblFroitas.setForeground(new java.awt.Color(204, 0, 102));
        lblFroitas.setText("FROITAS");

        bombasComidas.setBackground(new java.awt.Color(0, 204, 255));
        bombasComidas.setFont(new java.awt.Font("Miriam Libre", 3, 24)); // NOI18N
        bombasComidas.setForeground(new java.awt.Color(153, 0, 204));
        bombasComidas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bombasComidas.setText("0");
        bombasComidas.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(102, 51, 0)));
        bombasComidas.setOpaque(true);

        lblTempo.setFont(new java.awt.Font("Reem Kufi", 3, 24)); // NOI18N
        lblTempo.setForeground(new java.awt.Color(255, 255, 0));
        lblTempo.setText("TEMPO");

        tempoXogado.setBackground(new java.awt.Color(0, 204, 255));
        tempoXogado.setFont(new java.awt.Font("Miriam Libre", 3, 24)); // NOI18N
        tempoXogado.setForeground(new java.awt.Color(153, 0, 204));
        tempoXogado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tempoXogado.setText("0");
        tempoXogado.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(102, 51, 0)));
        tempoXogado.setOpaque(true);

        froitasComidas.setBackground(new java.awt.Color(0, 204, 255));
        froitasComidas.setFont(new java.awt.Font("Miriam Libre", 3, 24)); // NOI18N
        froitasComidas.setForeground(new java.awt.Color(153, 0, 204));
        froitasComidas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        froitasComidas.setText("0");
        froitasComidas.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(102, 51, 0)));
        froitasComidas.setOpaque(true);

        bPausa.setBackground(new java.awt.Color(0, 204, 255));
        bPausa.setFont(new java.awt.Font("Reem Kufi", 0, 24)); // NOI18N
        bPausa.setForeground(new java.awt.Color(102, 0, 102));
        bPausa.setText("PAUSE");
        bPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPausaActionPerformed(evt);
            }
        });

        puntosObtidos.setBackground(new java.awt.Color(0, 204, 255));
        puntosObtidos.setFont(new java.awt.Font("Miriam Libre", 3, 24)); // NOI18N
        puntosObtidos.setForeground(new java.awt.Color(153, 0, 204));
        puntosObtidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntosObtidos.setText("0");
        puntosObtidos.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(102, 51, 0)));
        puntosObtidos.setOpaque(true);

        lblPuntuacion.setFont(new java.awt.Font("Reem Kufi", 3, 24)); // NOI18N
        lblPuntuacion.setForeground(new java.awt.Color(0, 255, 255));
        lblPuntuacion.setText("PUNTUACIÓN");

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bombasComidas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tempoXogado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPuntuacion)
                            .addComponent(puntosObtidos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFroitas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBombas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(froitasComidas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tituloMenuSerpe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bPausa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bombasComidas, froitasComidas, lblBombas, lblFroitas, lblPuntuacion, lblTempo, puntosObtidos, tempoXogado});

        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(tituloMenuSerpe)
                .addGap(33, 33, 33)
                .addComponent(bPausa)
                .addGap(40, 40, 40)
                .addComponent(lblPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(puntosObtidos, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lblFroitas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(froitasComidas, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lblBombas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(bombasComidas, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lblTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(tempoXogado, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        panelXogo.setLocation(250, 0);
        panelXogo.setBackground(new java.awt.Color(182, 255, 182));
        panelXogo.setMaximumSize(new java.awt.Dimension(900, 900));
        panelXogo.setMinimumSize(new java.awt.Dimension(900, 900));
        panelXogo.setPreferredSize(new java.awt.Dimension(900, 900));
        panelXogo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelXogoKeyPressed(evt);
            }
        });

        imagen.setLocation(0, 0);
        try{
            imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/TableroSerpe.jpg"))); // NOI18N
        }catch (NullPointerException e){
            JOptionPane.showMessageDialog(this, "Erro ao cargar o tablero do Xogo.");
        }

        panelFinXogo.setLocation(200, 200);
        panelFinXogo.setVisible(false);
        panelFinXogo.setBackground(new java.awt.Color(102, 204, 0));
        panelFinXogo.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(80, 40, 0)));
        panelFinXogo.setMaximumSize(new java.awt.Dimension(500, 500));
        panelFinXogo.setMinimumSize(new java.awt.Dimension(500, 500));
        panelFinXogo.setPreferredSize(new java.awt.Dimension(500, 500));

        tituloFinXogo.setBackground(new java.awt.Color(153, 0, 153));
        tituloFinXogo.setFont(new java.awt.Font("Trebuchet MS", 3, 70)); // NOI18N
        tituloFinXogo.setForeground(new java.awt.Color(255, 0, 204));
        tituloFinXogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloFinXogo.setText("FIN DO XOGO");

        bPantallaInicial.setBackground(new java.awt.Color(102, 204, 255));
        bPantallaInicial.setFont(new java.awt.Font("Reem Kufi", 0, 24)); // NOI18N
        bPantallaInicial.setForeground(new java.awt.Color(102, 0, 102));
        bPantallaInicial.setText("PANTALLA INICIAL");
        bPantallaInicial.setToolTipText("");
        bPantallaInicial.setMaximumSize(new java.awt.Dimension(310, 50));
        bPantallaInicial.setMinimumSize(new java.awt.Dimension(310, 50));
        bPantallaInicial.setPreferredSize(new java.awt.Dimension(310, 50));
        bPantallaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPantallaInicialActionPerformed(evt);
            }
        });

        bNovaPartida.setBackground(new java.awt.Color(102, 204, 255));
        bNovaPartida.setFont(new java.awt.Font("Reem Kufi", 0, 24)); // NOI18N
        bNovaPartida.setForeground(new java.awt.Color(102, 0, 102));
        bNovaPartida.setText("NOVA PARTIDA");
        bNovaPartida.setMaximumSize(new java.awt.Dimension(310, 50));
        bNovaPartida.setMinimumSize(new java.awt.Dimension(310, 50));
        bNovaPartida.setPreferredSize(new java.awt.Dimension(310, 50));
        bNovaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNovaPartidaActionPerformed(evt);
            }
        });

        bGardarPuntuacion.setBackground(new java.awt.Color(102, 204, 255));
        bGardarPuntuacion.setFont(new java.awt.Font("Reem Kufi", 0, 24)); // NOI18N
        bGardarPuntuacion.setForeground(new java.awt.Color(102, 0, 102));
        bGardarPuntuacion.setText("GARDAR PUNTUACIÓN");
        bGardarPuntuacion.setMaximumSize(new java.awt.Dimension(310, 50));
        bGardarPuntuacion.setMinimumSize(new java.awt.Dimension(310, 50));
        bGardarPuntuacion.setPreferredSize(new java.awt.Dimension(310, 50));
        bGardarPuntuacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGardarPuntuacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFinXogoLayout = new javax.swing.GroupLayout(panelFinXogo);
        panelFinXogo.setLayout(panelFinXogoLayout);
        panelFinXogoLayout.setHorizontalGroup(
            panelFinXogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinXogoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelFinXogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFinXogoLayout.createSequentialGroup()
                        .addComponent(tituloFinXogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(128, 128, 128))
                    .addGroup(panelFinXogoLayout.createSequentialGroup()
                        .addGroup(panelFinXogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bPantallaInicial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(bNovaPartida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bGardarPuntuacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        panelFinXogoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bGardarPuntuacion, bNovaPartida, bPantallaInicial});

        panelFinXogoLayout.setVerticalGroup(
            panelFinXogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinXogoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(tituloFinXogo)
                .addGap(55, 55, 55)
                .addComponent(bPantallaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(bNovaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(bGardarPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        panelFinXogoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bGardarPuntuacion, bNovaPartida, bPantallaInicial});

        javax.swing.GroupLayout panelXogoLayout = new javax.swing.GroupLayout(panelXogo);
        panelXogo.setLayout(panelXogoLayout);
        panelXogoLayout.setHorizontalGroup(
            panelXogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelXogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelXogoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelFinXogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelXogoLayout.setVerticalGroup(
            panelXogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagen)
            .addGroup(panelXogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelXogoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelFinXogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout juegoLayout = new javax.swing.GroupLayout(juego);
        juego.setLayout(juegoLayout);
        juegoLayout.setHorizontalGroup(
            juegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, juegoLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelXogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        juegoLayout.setVerticalGroup(
            juegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(juegoLayout.createSequentialGroup()
                .addGroup(juegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelXogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        getContentPane().add(juego, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelPuntuacions.setVisible(false);
        panelPuntuacions.setBackground(new java.awt.Color(182, 255, 182));
        panelPuntuacions.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(80, 40, 0)));
        panelPuntuacions.setMaximumSize(new java.awt.Dimension(1150, 900));
        panelPuntuacions.setMinimumSize(new java.awt.Dimension(1150, 900));
        panelPuntuacions.setPreferredSize(new java.awt.Dimension(1150, 900));

        tituloSerpe1.setBackground(new java.awt.Color(153, 0, 153));
        tituloSerpe1.setFont(new java.awt.Font("Trebuchet MS", 3, 70)); // NOI18N
        tituloSerpe1.setForeground(new java.awt.Color(153, 0, 153));
        tituloSerpe1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloSerpe1.setText("PUNTUACIÓNS");

        bVolverInicio.setBackground(new java.awt.Color(102, 204, 255));
        bVolverInicio.setFont(new java.awt.Font("Reem Kufi", 0, 24)); // NOI18N
        bVolverInicio.setForeground(new java.awt.Color(102, 0, 102));
        bVolverInicio.setText("VOLVER A PANTALLA INICIAL");
        bVolverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverInicioActionPerformed(evt);
            }
        });

        jTablePuntuacions.setBackground(new java.awt.Color(0, 204, 51));
        jTablePuntuacions.setFont(new java.awt.Font("Reem Kufi", 0, 14)); // NOI18N
        jTablePuntuacions.setForeground(new java.awt.Color(0, 0, 204));
        jTablePuntuacions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "JUGADOR", "PUNTUACIÓN", "FROITAS", "BOMBAS", "TEMPO", "DATA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePuntuacions.setFocusable(false);
        jTablePuntuacions.setGridColor(new java.awt.Color(204, 0, 0));
        jTablePuntuacions.setSelectionBackground(new java.awt.Color(255, 255, 0));
        jTablePuntuacions.setSelectionForeground(new java.awt.Color(0, 0, 204));
        jTablePuntuacions.setShowGrid(true);
        jScrollPane1.setViewportView(jTablePuntuacions);
        if (jTablePuntuacions.getColumnModel().getColumnCount() > 0) {
            jTablePuntuacions.getColumnModel().getColumn(0).setResizable(false);
            jTablePuntuacions.getColumnModel().getColumn(1).setResizable(false);
            jTablePuntuacions.getColumnModel().getColumn(2).setResizable(false);
            jTablePuntuacions.getColumnModel().getColumn(3).setResizable(false);
            jTablePuntuacions.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout panelPuntuacionsLayout = new javax.swing.GroupLayout(panelPuntuacions);
        panelPuntuacions.setLayout(panelPuntuacionsLayout);
        panelPuntuacionsLayout.setHorizontalGroup(
            panelPuntuacionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPuntuacionsLayout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(tituloSerpe1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(295, 295, 295))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPuntuacionsLayout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(bVolverInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(359, 359, 359))
            .addGroup(panelPuntuacionsLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jScrollPane1)
                .addGap(230, 230, 230))
        );
        panelPuntuacionsLayout.setVerticalGroup(
            panelPuntuacionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPuntuacionsLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(tituloSerpe1)
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(bVolverInicio)
                .addGap(110, 110, 110))
        );

        getContentPane().add(panelPuntuacions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelXogoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelXogoKeyPressed
        if (bPausa.isSelected()){
            if (evt.getKeyCode()==KeyEvent.VK_ESCAPE){
                despausar();
                bPausa.setSelected(false);
            }
        }
        else {
            if (evt.getKeyChar()=='w' || evt.getKeyChar()=='W' || evt.getKeyCode()==38){
                xogo.voltearSerpeArriba();
            }
            if (evt.getKeyChar()=='d' || evt.getKeyChar()=='D' || evt.getKeyCode()==39){
                xogo.voltearSerpeDereita();
            }
            if (evt.getKeyChar()=='s' || evt.getKeyChar()=='S' || evt.getKeyCode()==40){
               xogo.voltearSerpeAbaixo();
            }
            if (evt.getKeyChar()=='a' || evt.getKeyChar()=='A' || evt.getKeyCode()==37){
                xogo.voltearSerpeEsquerda();
            }if (evt.getKeyChar()==' '){
                xogo.avanzarSerpe();
            }
            
            if (evt.getKeyCode()==KeyEvent.VK_ESCAPE){
                pausar();
            }
        }
    }//GEN-LAST:event_panelXogoKeyPressed

    private void bIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIniciarActionPerformed
        iniciarXogo();
    }//GEN-LAST:event_bIniciarActionPerformed

    private void bPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPausaActionPerformed
        if (bPausa.isSelected()){
            pausar();
        }
        else{
            despausar();
        }
    }//GEN-LAST:event_bPausaActionPerformed

    private void bModoXogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModoXogoActionPerformed
        jDModoXogo.setVisible(true);
    }//GEN-LAST:event_bModoXogoActionPerformed

    private void bClasicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClasicoActionPerformed
        jDModoXogo.setVisible(false);
        xogo.setModoClasico(true);
    }//GEN-LAST:event_bClasicoActionPerformed

    private void bEsferaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEsferaActionPerformed
        jDModoXogo.setVisible(false);
        xogo.setModoClasico(false);
    }//GEN-LAST:event_bEsferaActionPerformed

    private void bPantallaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPantallaInicialActionPerformed
        pantallaInicial.setVisible(true);
        juego.setVisible(false);
        reiniciar();
    }//GEN-LAST:event_bPantallaInicialActionPerformed

    private void bNovaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNovaPartidaActionPerformed
        reiniciar();
        iniciarXogo();
    }//GEN-LAST:event_bNovaPartidaActionPerformed

    private void bGardarPuntuacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGardarPuntuacionActionPerformed
        jDGardarPuntuacion.setVisible(true);
    }//GEN-LAST:event_bGardarPuntuacionActionPerformed

    private void bIniciarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIniciarSesiónActionPerformed
        jDSesion.setVisible(true);
        panelInicioSesion.setVisible(true);
        panelRegistrarse.setVisible(false);
        lblUsuarioNonEncontrado.setText("");
    }//GEN-LAST:event_bIniciarSesiónActionPerformed

    private void bRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarseActionPerformed
        jDSesion.setVisible(true);
        panelInicioSesion.setVisible(false);
        panelRegistrarse.setVisible(true);
        lblUsuarioOcupado.setText("");
    }//GEN-LAST:event_bRegistrarseActionPerformed

    private void bConfirmarGardarPuntuacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConfirmarGardarPuntuacionActionPerformed
        boolean gardado=conexionBD.gardarDatos(xogo.getJugador(), xogo.getPuntuacion(), xogo.getFroitasComidas(), xogo.getBombasComidas(), xogo.getTempo());
        if (gardado){
            jDGardarPuntuacion.setVisible(false);
            bGardarPuntuacion.setEnabled(false);
            bGardarPuntuacion.setText("PUNTUACIÓN GARDADA");
        }
        lblUsuarioNonEncontrado.setText("");
        lblUsuarioOcupado.setText("");
    }//GEN-LAST:event_bConfirmarGardarPuntuacionActionPerformed

    private void bConfirmarInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConfirmarInicioSesionActionPerformed
        boolean usuarioRegistrado = conexionBD.comprobarUsuario(usuario.getText());
        boolean inicioSesion = conexionBD.iniciarSesion(usuario.getText(), contrasinal.getText());
        if (usuarioRegistrado){
            if (inicioSesion){
                jDSesion.setVisible(false);
                lblUsuarioNonEncontrado.setText("");
                xogo.setJugador(usuario.getText());
                lblComoUsuario.setText("Como " + xogo.getJugador());
            }
            else{
                lblUsuarioNonEncontrado.setText("Contrasinal incorrecto.");
            }
        }
        else{
            lblUsuarioNonEncontrado.setText("O usuario non existe.");
        }
        usuario.setText("");
        contrasinal.setText("");
    }//GEN-LAST:event_bConfirmarInicioSesionActionPerformed

    private void bConfirmarRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConfirmarRegistrarseActionPerformed
        boolean registro = conexionBD.registrarse(usuarioNovo.getText(), contrasinalNovo.getText());
        if (registro){
            jDSesion.setVisible(false);
            lblUsuarioOcupado.setText("");
        }
        else {
            lblUsuarioOcupado.setText("Nome de usuario ocupado.");
        }
        usuarioNovo.setText("");
        contrasinalNovo.setText("");
    }//GEN-LAST:event_bConfirmarRegistrarseActionPerformed

    private void bPuntuacionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPuntuacionsActionPerformed
        pantallaInicial.setVisible(false);
        panelPuntuacions.setVisible(true);
        DefaultTableModel tablaPuntuacions = (DefaultTableModel) jTablePuntuacions.getModel();
        for (int i = tablaPuntuacions.getRowCount()-1; i >=0 ; i--) {
            tablaPuntuacions.removeRow(i);
        }
        ArrayList<Object> partidas = conexionBD.obterPuntuacións();
        Iterator<Object> iterPartidas =partidas.iterator();
        while (iterPartidas.hasNext()){
            tablaPuntuacions.addRow((Object[]) iterPartidas.next());
        }
        jTablePuntuacions.setModel(tablaPuntuacions);
    }//GEN-LAST:event_bPuntuacionsActionPerformed

    private void bSairXogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairXogoActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bSairXogoActionPerformed

    private void bVolverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverInicioActionPerformed
        pantallaInicial.setVisible(true);
        panelPuntuacions.setVisible(false);
    }//GEN-LAST:event_bVolverInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }
    
    private void iniciarXogo(){
        pantallaInicial.setVisible(false);
        juego.setVisible(true);
        xogo.iniciarPartida();
        panelXogo.setFocusable(true);
        despausar();
    }
    
    public void finDoXogo(){
        panelFinXogo.setVisible(true);
        pausar();
        bPausa.setVisible(false);
        panelXogo.setFocusable(false);
        bGardarPuntuacion.setEnabled(true);
        bGardarPuntuacion.setText("GARDAR PUNTUACIÓN");
    }
    
    private void pausar(){
        bPausa.setSelected(true);
        bPausa.setText("START");
        timer.stop();
        tempoXogo.stop();
        panelXogo.requestFocus();
    }
    
    private void despausar(){
        bPausa.setSelected(false);
        bPausa.setText("PAUSE");
        timer.restart();
        tempoXogo.restart();
        panelXogo.requestFocus();
    }
    
    private void reiniciar(){
        xogo.borrarCadrados();
        bPausa.setVisible(true);
        panelFinXogo.setVisible(false);
        xogo.setPuntuacion(0);
        xogo.setFroitasComidas(0);
        xogo.setBombasComidas(0);
        xogo.setTempo(0);
        establecerPuntos(0);
        engadirFroitas(0);
        engadirBombas(0);
        engadirTempo(0);
        delay=500;
    }
    
    /**
     * Pinta no panelXogo a label do cadrado que lle pasan
     * e pon a label da imaxe por debaixo dos demais componentes do panel.
     * @param cadrado 
     */
    public void pintarCadrado(Cadrado cadrado){
        panelXogo.add(cadrado.getLblCadrado());
        panelXogo.updateUI();
        panelXogo.setComponentZOrder(imagen, panelXogo.getComponentCount()-1);
    }
    
    public void borrarCadrado(Cadrado cadrado){
        panelXogo.remove(cadrado.getLblCadrado());
        panelXogo.updateUI();
    }
    
    private void crearTempoXogo(){
        tempoXogo=new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int tempoXogo=xogo.getTempo();
                tempoXogo++;
                xogo.setTempo(tempoXogo);
                engadirTempo(tempoXogo);
            }
        });
    }
    
    private void crearTimerVelocidade(){
        timer=new Timer(delay, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                xogo.avanzarSerpe();
                panelXogo.requestFocus();
            }
        });
    }
    
    public void engadirFroitas(int froitas){
        froitasComidas.setText(froitas+"");
    }
    
    public void engadirBombas(int bombas){
        bombasComidas.setText(bombas+"");
    }
    
    public void establecerPuntos(int puntos){
        puntosObtidos.setText(puntos+"");
    }
    
    private void engadirTempo(int tempoXogo){
        tempoXogado.setText(tempoXogo+"");
        xogo.setTempo(tempoXogo);
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = null;
        try{
            retValue = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/recursos/CabezaSerpe.png"));
        }catch (NullPointerException e){}
        return retValue;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClasico;
    private javax.swing.JButton bConfirmarGardarPuntuacion;
    private javax.swing.JButton bConfirmarInicioSesion;
    private javax.swing.JButton bConfirmarRegistrarse;
    private javax.swing.JButton bEsfera;
    private javax.swing.JButton bGardarPuntuacion;
    private javax.swing.JButton bIniciar;
    private javax.swing.JButton bIniciarSesión;
    private javax.swing.JButton bModoXogo;
    private javax.swing.JButton bNovaPartida;
    private javax.swing.JButton bPantallaInicial;
    private javax.swing.JToggleButton bPausa;
    private javax.swing.JButton bPuntuacions;
    private javax.swing.JButton bRegistrarse;
    private javax.swing.JButton bSairXogo;
    private javax.swing.JButton bVolverInicio;
    private javax.swing.JLabel bombasComidas;
    private javax.swing.JTextField contrasinal;
    private javax.swing.JTextField contrasinalNovo;
    private javax.swing.JLabel froitasComidas;
    private javax.swing.JLabel imagen;
    private javax.swing.JDialog jDGardarPuntuacion;
    private javax.swing.JDialog jDModoXogo;
    private javax.swing.JDialog jDSesion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePuntuacions;
    private javax.swing.JPanel juego;
    private javax.swing.JLabel lblBombas;
    private javax.swing.JLabel lblComoUsuario;
    private javax.swing.JLabel lblContrasinal;
    private javax.swing.JLabel lblContrasinalNovo;
    private javax.swing.JLabel lblFroitas;
    private javax.swing.JLabel lblPuntuacion;
    private javax.swing.JLabel lblTempo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuarioNonEncontrado;
    private javax.swing.JLabel lblUsuarioNovo;
    private javax.swing.JLabel lblUsuarioOcupado;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel panelFinXogo;
    private javax.swing.JPanel panelGardarPuntuacion;
    private javax.swing.JPanel panelInicioSesion;
    private javax.swing.JPanel panelModoXogo;
    private javax.swing.JPanel panelPuntuacions;
    private javax.swing.JPanel panelRegistrarse;
    private javax.swing.JPanel panelXogo;
    private javax.swing.JPanel pantallaInicial;
    private javax.swing.JLabel puntosObtidos;
    private javax.swing.JLabel tempoXogado;
    private javax.swing.JLabel tituloFinXogo;
    private javax.swing.JLabel tituloInicioSesion;
    private javax.swing.JLabel tituloMenuSerpe;
    private javax.swing.JLabel tituloRegistrarse;
    private javax.swing.JLabel tituloSerpe;
    private javax.swing.JLabel tituloSerpe1;
    private javax.swing.JTextField usuario;
    private javax.swing.JTextField usuarioNovo;
    // End of variables declaration//GEN-END:variables
}
